export const RETRIEVE_STUDENTS = "RETRIEVE_STUDENTS";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

export const RETRIEVE_SUBJECTS = "RETRIEVE_SUBJECTS";
export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";

export const RETRIEVE_EXAMS = "RETRIEVE_EXAMS";
export const CREATE_EXAM = "CREATE_EXAM";
export const UPDATE_EXAM = "UPDATE_EXAM";
export const DELETE_EXAM = "DELETE_EXAM";

export const RETRIEVE_SCORES = "RETRIEVE_SCORES";
export const CREATE_SCORE = "CREATE_SCORE";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const DELETE_SCORE = "DELETE_SCORE";